input_file:
    tsv: "resources/raw/metadata.tsv"
    fasta: "resources/raw/sequences.fasta"

output_dirs:
    - "results"
    - "results/{build_name}/tree"
    - "results/{build_name}/augur"
    - "results/{build_name}/filter"
    - "results/{build_name}/align"
    - "results/{build_name}/refine"

dataset_config:
  L/tefe:
    dataset_files: "resources/L/tefe"
    min_length: 5110
    max_length: 6814
    genes: ["L"]
  L/refseq:
    dataset_files: "resources/L/refseq"
    min_length: 5134
    max_length: 6846
    genes: ["L"]
  M/tefe:
    dataset_files: "resources/M/tefe"
    min_length: 3509
    max_length: 4387
    genes: ["M"]
  M/refseq:
    dataset_files: "resources/M/refseq"
    min_length: 3508
    max_length: 4385
    genes: ["M"]
  S/tefe:
    dataset_files: "resources/S/tefe"
    min_length: 755
    max_length: 944
    genes: ["N","NSs"]
  S/refseq:
    dataset_files: "resources/S/refseq"
    min_length: 603
    max_length: 754
    genes: ["N","NSs"]

resources:
  default:
    mem_mb: 60000
    threads: 20
  minimal:
    mem_mb: 10000
    threads: 1
  align:
    mem_mb: 100000
    threads: 60

filter:
    group_by: "country month"
    sequences_per_group: "10"

strain_id_field: "accession"